// Generated by Xata Codegen 0.18.0. Please do not edit.
const {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} = require("@xata.io/client");
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "Iro-histories",
    columns: [
      { name: "name", type: "string" },
      { name: "DOB", type: "datetime" },
      { name: "brief", type: "text" },
      { name: "tag", type: "string" },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Samuel-Peter-s-workspace-nd0ikq.us-east-1.xata.sh/db/iro",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */

export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance = undefined;

/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
